---
openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8081
  description: Generated server url
paths:
  "/api/v1/customers/{id}":
    get:
      tags:
      - customer-controller
      operationId: getCustomer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/CustomerResponseDTO"
    put:
      tags:
      - customer-controller
      operationId: update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CustomerUpdateDTO"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/CustomerResponseDTO"
    delete:
      tags:
      - customer-controller
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
  "/api/v1/customers":
    get:
      tags:
      - customer-controller
      operationId: listCustomer
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Customer"
    post:
      tags:
      - customer-controller
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CustomerRequestDTO"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/CustomerResponseDTO"
components:
  schemas:
    CustomerUpdateDTO:
      type: object
      properties:
        gender:
          type: string
        identification:
          type: string
        address:
          type: string
        phone:
          type: string
        password:
          type: string
        state:
          type: boolean
        name:
          type: string
    CustomerResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        identification:
          type: string
        gender:
          type: string
        address:
          type: string
        phone:
          type: string
        state:
          type: boolean
        name:
          type: string
    CustomerRequestDTO:
      type: object
      properties:
        customerId:
          type: integer
          format: int64
        password:
          type: string
          minLength: 1
        gender:
          type: string
        identification:
          type: string
        address:
          type: string
        phone:
          type: string
        name:
          type: string
      required:
      - customerId
      - password
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        gender:
          type: string
        identification:
          type: string
        address:
          type: string
        phone:
          type: string
        customerId:
          type: integer
          format: int64
        password:
          type: string
        state:
          type: boolean
